# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fhdaisy',
                'doc_host': 'https://AnswerDotAI.github.io',
                'git_url': 'https://github.com/AnswerDotAI/fhdaisy',
                'lib_path': 'fhdaisy'},
  'syms': {'fhdaisy.core': {'fhdaisy.core.foo': ('core.html#foo', 'fhdaisy/core.py')}}}
