"""Builder API used behind the scenes to create the basic components"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['daisy_link', 'tw_scr', 'daisy_hdrs', 'mk_previewer', 'hyphens2camel', 'mk_compfn']

# %% ../nbs/00_core.ipynb 2
from fastcore.utils import *
from fasthtml.common import *
import fasthtml.components as fh
from fasthtml.jupyter import *

import inspect

# %% ../nbs/00_core.ipynb 5
daisy_link = Link(href='https://cdn.jsdelivr.net/npm/daisyui@5', rel='stylesheet', type='text/css')
tw_scr = Script(src='https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4')
daisy_hdrs = (daisy_link, tw_scr)

# %% ../nbs/00_core.ipynb 6
def mk_previewer(app=None, cls=f'max-w-lg'):
    xcls = cls
    if not app: app=FastHTML(hdrs=daisy_hdrs)
    def p(*c, cls='', **kw):
        return HTMX(Div(cls=f'{xcls} {cls}')(*c), app=app, host=None, port=None, **kw)
    return p

# %% ../nbs/00_core.ipynb 11
def hyphens2camel(x): return ''.join(o.title() for o in x.split('-'))
hyphens2camel('chat-bubble')

# %% ../nbs/00_core.ipynb 13
_neg_twu_pfxs = set('mt ml mr mb mx my translate rotate scale skew inset top bottom left right z space'.split())
def _is_neg_twu(x): return x[0]=='-' and len(parts:=x[1:].split('-'))>=2 and parts[0] in _neg_twu_pfxs

# %% ../nbs/00_core.ipynb 15
def mk_compfn(compcls, tag=None, name=None, xcls='', **compkw):
    if not name: name=hyphens2camel(compcls)
    if not tag: tag=name
    compfunc = getattr(fh, tag)

    def fn(*c, cls='', **kw):
        cls = ' '.join(f'{compcls if x[0]=="-" and not _is_neg_twu(x) else ""}{x}' for x in cls.split())
        return compfunc(*c, cls=f'{compcls} {cls} {xcls}', **compkw, **kw)

    fn.__name__ = name
    inspect.currentframe().f_back.f_globals[name] = fn
