# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_xtras.ipynb.

# %% auto 0
__all__ = ['ChatTurn', 'ChatPair', 'mk_dropdown', 'mk_fab', 'mk_swap', 'mk_accordion_item', 'mk_accordion']

# %% ../nbs/01_xtras.ipynb 1
from fastcore.utils import *
from fasthtml.common import *
from .comp import *
import fasthtml.components as fh

# %% ../nbs/01_xtras.ipynb 5
def ChatTurn(msg, cls='', bubblecls='', **kw):
    return Chat(cls=cls, **kw)(
        ChatBubble(msg, cls=bubblecls)
    )

# %% ../nbs/01_xtras.ipynb 7
def ChatPair(q, a):
    return ChatTurn(q, cls='-start'), ChatTurn(a, cls='-end', bubblecls='-primary')

# %% ../nbs/01_xtras.ipynb 13
def mk_dropdown(summary, items, summcls='', cls='', **kw):
    return Dropdown(
        fh.Summary(summary, cls=summcls),
        DropdownContent(*items, cls=f'{cls} menu', **kw)
    )

# %% ../nbs/01_xtras.ipynb 17
def mk_fab(txt, main, items, maincls='-success', btncls='-lg -circle', cls='', **kw):
    return Fab(
        Btn(txt, tabindex='0', cls=f'{maincls} {btncls}'),
        Btn(main, cls=f'fab-main-action {btncls}'),
        *[Btn(item, cls=btncls) for item in items],
        cls=cls, **kw
    )

# %% ../nbs/01_xtras.ipynb 21
def mk_swap(on, off, cls='', **kw):
    return Swap(
        fh.Input(type='checkbox'),
        SwapOn(on),
        SwapOff(off),
        cls=cls, **kw
    )

# %% ../nbs/01_xtras.ipynb 27
def mk_accordion_item(title, content, name='accordion', checked=False, cls='', titlecls='', contentcls='', **kw):
    return Collapse(
        fh.Input(type='radio', name=name, checked=checked),
        CollapseTitle(title, cls=titlecls),
        CollapseContent(content, cls=contentcls),
        cls=cls, **kw)

# %% ../nbs/01_xtras.ipynb 31
def mk_accordion(*items, name=None, cls='', itemcls='', titlecls='', contentcls='', itemkw=None, **kw):
    if not name: name = f'acc-{id(items)}'
    if not itemkw: itemkw={}
    ais = [mk_accordion_item(*o, name=name, checked=i==0, cls=itemcls, titlecls=titlecls, contentcls=contentcls, **itemkw)
        for i,o in enumerate(items)]
    return Join(*ais, cls=cls, **kw)
